#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          IXUnitLex1
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Runs IXUnitLex1
# Description:       Runs IXUnitLex1
### END INIT INFO

# Author: Sean Montgomery <produceconsumerobot@gmail.com>

DESC="IXUnitLex1"
NAME=IXUnitLex1
DAEMON=/home/pi/openFrameworks/apps/livestream/$NAME/bin/$NAME
