#!/bin/bash

ipAddress=$(hostname -I)
echo $ipAddress
echo ""
while read ips; do
  if [[ $ipAddress == "$ips"* ]]; then
    echo "*" $ips
  else
    echo $ips ": sudo systemctl stop IXUnitLex1.service"
    #$(cat sudo systemctl stop IXUnitLex1.service | ssh pi@$ips)
    ssh pi@$ips -T 'sudo systemctl stop IXUnitLex1.service'
    #ssh -t pi@$ips << HERE
    #  sudo systemctl stop IXUnitLex1.service
    #HERE
  fi
  #echo $ipAddress
done <piIPs

